name: Gradle Build and Merge Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configura el repositorio
    - name: Check out code
      uses: actions/checkout@v3

    # Configura Java y Gradle
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21' # Cambia según tu versión de Java
        distribution: 'temurin'
        cache: 'gradle'


    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Compila el código con Gradle
    - name: Build with Gradle
      run: ./gradlew build -x test -x lint

  # Validar conflictos de merge
  merge-check:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Validate merge conflicts
      run: |
        git fetch --no-tags --prune --depth=1 origin main
        git merge --no-commit --no-ff origin/main || echo "Conflict with main branch!"
        git merge --no-commit --no-ff origin/develop || echo "Conflict with develop branch!"
